### PR TITLE
Highlight sticky nav in posts and add link underlines

### LINKED ISSUE #117: Links in callouts are difficult to see
See for example https://kedro.org/blog/development-principles-for-opinionated-teams

image

### PR DESCRIPTION
**Pull request by tynandebold**
## Description

Resolves #117.

## Development notes

Using the awesome `IntersectionObserver` and some cool stuff with React `refs` and JS `Map`.

## QA notes

Here's all the newness: 

image

Play around with the deployed URL to get a feel for yourself!

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Added tests to cover my changes, where applicable

### CODE REVIEW

**Review by stichbury — APPROVED** [review]
Really slick, thank you 🙏

**Comment by tynandebold** [comment]
Good catch, Steph! Can you please try it again? I've made an update that should fix what you highlighted.

**Comment by stephkaiser** [comment]
> Good catch, Steph! Can you please try it again? I've made an update that should fix what you highlighted.

Nice, it works as expected now! 😎

**Review by stephkaiser — APPROVED** [review]

**Review by Mackay031 — APPROVED** [review]

**Comment by Mackay031** [comment]
Lovely stuff team.

**Pull request merged**
