### PR TITLE
Update Hero CTA buttons and Ready To Start section

### LINKED ISSUE #173: The two calls to action on top are too similar
## Description

When I first saw the Kedro website, I was very confused about the two calls to action:

image

I wanted to "Get started" _and_ I also wanted to take the tutorial... So I remember thinking "whatever, I'll click any of the buttons".

## Possible solutions

One idea could be to rename "Get started" to something that alludes to the installation instructions, like "Install", "Install Kedro", or similar. Still not ideal for me to have 2 calls to action, but marginally better than what we have now?

A more interesting idea would be though to have only one button (can be "get started" or "go to the documentation" or "take the tutorial") and a box right above or below that contains a `pip install kedro` and `conda install -c conda-forge kedro` so that visitors don't even need to click a button to get to the installation instructions. A bit more design work, but potentially more helpful. And also _makes it crystal clear that Kedro is pip-installable, hence Python-based and open-source_.

Ideally all this would be **above the fold**.

### PR DESCRIPTION
**Pull request by tynandebold**
## Description

Resolves #173

## Development notes

I believe I've covered everything stated in #173.

## QA notes

Check the deployed link and see if I missed anything.

@stephkaiser might want to take a quick look at the code formatting in the `Ready to start?` section. 

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Added tests to cover my changes, where applicable

### CODE REVIEW

**Comment by stichbury** [comment]
The preview looks great to me. Just one thing @tynandebold...there is an [extra line of copy](https://github.com/kedro-org/kedro-website/issues/173#issuecomment-1808303396) after the code snippets.

"For more details, see the [set up documentation](https://docs.kedro.org/en/stable/get_started/install.html) or watch the video". (where the link to the video is TBD, but should come today or soon).

The copy will sit between the code and the "Take the tutorial" lozenge and be in normal font, please.

Shall we see how that looks and I agree we need to get design to confirm, so ask @stephkaiser on her return.

**Review by stichbury — CHANGES_REQUESTED** [review]
Looks really great -- I like the code!
Requested a change to add extra copy line.

**Comment by tynandebold** [comment]
Sorry I missed that line! Updated now.

**Comment by stichbury** [comment]
> Sorry I missed that line! Updated now.

Very nice, thanks! All good for me, just waiting on that link now. Thanks!

**Review by stichbury — APPROVED** [review]
Good for me, once the link is available for that video.

**Review by astrojuanlu — APPROVED** [review]
At first I thought that the pattern of using a section at the bottom of the website was interesting... and then I realized that section was there all along (had completely forgotten about that part of the website)

I'm +1 because this is a minimal effort revamp and it's an noticeable improvement over what we had, even though it's not exactly what I had in mind (which initially was having the `pip install` command above the fold).

We can tackle that in the future.

**Review by stephkaiser — APPROVED** [review]

**Pull request merged**
